### ISSUE TITLE
Decryption failed (Wrong folders names)

### ISSUE THREAD

**Issue by mauronofrio** [notsyncing/android_device_xiaomi_polaris#11]
Hi, i'm trying to build a twrp for enchilada (oneplus 6) and i'm having a problem with decryption, the folders names are wrong. The tree was used to make a perfect twrp and i'm not understanding Where am I doing wrong. I tried to ask to tree's dev but he doesn't answer me. I'm using branch android 8.1, with minimal twrp android 8.1, device qcom common android 8.0 by teamwin and bootable recovery android 9.0.
This is the device tree: https://github.com/mauronofrio/android_device_oneplus_enchilada

**Comment by notsyncing** [comment]
You can start with logs and see what's going on: twrp logs, logcat and dmesg. Are you building twrp for android 9.0 and unable to decrypt? If so, you can see my issue on twrp here: https://github.com/omnirom/android_bootable_recovery/issues/235#issuecomment-423921489
Hope that would help you.

**Comment by notsyncing** [comment]
Also, I don't have an oneplus 6, and I'm using omni-9.0 to build twrp, which may not suitable for your case.
