### ISSUE TITLE
Compiling problems topic.

### ISSUE THREAD

**Issue by mauronofrio** [notsyncing/android_device_xiaomi_polaris#13]
ninja: error: '/home/mauro/omni8-min-normal/out/target/product/dipper/obj/SHARED_LIBRARIES/libcryptfs_hw_intermediates/export_includes', needed by '/home/mauro/omni9-min-normal/out/target/product/dipper/obj/SHARED_LIBRARIES/libcryptfslollipop_intermediates/import_includes', missing and no known rule to make it

Got all times this error trying to compile this twrp, can you help me?

**Comment by notsyncing** [comment]
Why `omni8-min-normal` then `omni9-min-normal`? Did you switched directories without re-executing `. build/envsetup.sh` and `lunch omni_polaris-eng`?

**Comment by mauronofrio** [comment]
No no, i have the same.problem on omni-8, i reported back the omni-8 error, i wanted tho change fhe path name and i forgot that name.
I'm seeing is related to: TARGET_HW_DISK_ENCRYPTION := true

**Comment by simonsmh** [comment]
There is a android-8.1 branch if you really want to build it, but I personally suggest you use latest omni 9 to build this recovery.

**Comment by mauronofrio** [comment]
@notsyncing @simonsmh i tried to compile it under omni-9.0, i built some others TWRP under omni-8.1 and i got the same problem, derivated from TARGET_HW_DISK_ENCRYPTION := true . Let's focus on the build error, forget about my paths.

Now i tried with full omni 9 source, but i have the same problem:
[ 99% 961/962] glob vendor/omni/overlay/common/**/*
ninja: error: '/home/mauro/omni9/out/target/product/polaris/obj/SHARED_LIBRARIES/libcryptfs_hw_intermediates/export_includes', needed by '/home/mauro/omni9/out/target/product/polaris/obj/SHARED_LIBRARIES/libcryptfslollipop_intermediates/import_includes', missing and no known rule to make it
01:36:43 ninja failed with: exit status 1

Edit: Why did you close the issue without solving it?

**Comment by notsyncing** [comment]
Do you have `TeamWin/android_device_qcom_common` checked out into `device/qcom/common`? If so, you could try remove `LOCAL_PROPRIETARY_MODULE := true` from `device/qcom/common/cryptfs_hw/Android.mk` and try again. If not, you can add this line to your `manifest.xml` and see if it works:

`  <project name="TeamWin/android_device_qcom_common" path="device/qcom/common" remote="github" revision="android-8.0" />`

**Comment by mauronofrio** [comment]
I already have it, i can try removing LOCAL_PROPRIETARY_MODULE := true, i will try it soon

**Comment by notsyncing** [comment]
Oh, looks like that we do not need `TARGET_HW_DISK_ENCRYPTION` at all, it's for FDE, while our device is FBE!

I just tried a build without `TARGET_HW_DISK_ENCRYPTION` and it decrypts well.

**Comment by mauronofrio** [comment]
Ok, are you able to change the brightness values when you are in twrp?

**Comment by notsyncing** [comment]
Yes

**Comment by mauronofrio** [comment]
I ported it to xiaomi mi 8 dipper and seems there are some problems on the global roms, have you got this problem too?

**Comment by simonsmh** [comment]
What the problems are?

**Comment by mauronofrio** [comment]
It freeze at twrp boot logo, adb is working and i have also some logs

**Comment by simonsmh** [comment]
You might want to extract all blobs from your own device instead from ours in the repo.
Also please put logs here, thanks.

**Comment by mauronofrio** [comment]
I used all blobs from my device and from the global rom. On others roms it works well, only with the global it is not working. Here the logs:

```
01-27 11:34:03.243   522   522 E cutils-trace: Error opening trace file: No such file or directory (2)
01-27 11:34:03.243   517   517 E cutils-trace: Error opening trace file: No such file or directory (2)
01-27 11:34:03.256   517   517 W hwservicemanager: getTransport: Cannot find entry android.hidl.manager@1.0::IServiceManager/default in either framework or device manifest.
01-27 11:34:03.256   517   517 E SELinux : avc:  denied  { find } for interface=android.hardware.keymaster::IKeymasterDevice pid=522 scontext=u:r:recovery:s0 tcontext=u:object_r:hal_keymaster_hwservice:s0 tclass=hwservice_manager permissive=1
01-27 11:34:03.257   517   517 W hwservicemanager: getTransport: Cannot find entry android.hardware.keymaster@4.0::IKeymasterDevice/default in either framework or device manifest.
01-27 11:34:03.258   522   522 I ServiceManagement: getService: Trying again for android.hardware.keymaster@3.0::IKeymasterDevice/default...
01-27 11:34:04.258   522   522 W ServiceManagement: Waited one second for android.hardware.keymaster@3.0::IKeymasterDevice/default. Waiting another...
01-27 11:34:06.258   522   522 I chatty  : uid=0(root) /sbin/recovery identical 2 lines
01-27 11:34:07.258   522   522 W ServiceManagement: Waited one second for android.hardware.keymaster@3.0::IKeymasterDevice/default. Waiting another...
01-27 11:34:08.090   573   575 I adbd    : initializing functionfs
01-27 11:34:08.090   573   575 I adbd    : opening control endpoint /dev/usb-ffs/adb/ep0
01-27 11:34:08.092   573   575 I adbd    : functionfs successfully initialized
01-27 11:34:08.092   573   575 I adbd    : registering usb transport
01-27 11:34:08.092   573   577 E cutils-trace: Error opening trace file: No such file or directory (2)
01-27 11:34:08.258   522   522 W ServiceManagement: Waited one second for android.hardware.keymaster@3.0::IKeymasterDevice/default. Waiting another...
```

This is from tmp/recovery.log:

```
Starting TWRP 3.2.3-0-2315e859 on Mon Apr 13 01:02:20 1970
 (pid 521)
BOARD_HAS_NO_REAL_SDCARD := true
RECOVERY_SDCARD_ON_DATA := true
I:Lun file '/sys/class/android_usb/android0/f_mass_storage/lun0/file' does not exist, USB storage mode disabled
TW_INCLUDE_CRYPTO := true
I:TW_BRIGHTNESS_PATH := /sys/class/backlight/panel0-backlight/brightness
I:Found brightness file at '/sys/class/backlight/panel0-backlight/brightness'
I:TWFunc::Set_Brightness: Setting brightness control to 420
I:LANG: en
Starting the UI...
setting DRM_FORMAT_BGRA8888 and GGL_PIXEL_FORMAT_BGRA_8888
setting DRM_FORMAT_ARGB8888 and GGL_PIXEL_FORMAT_RGBA_8888
setting DRM_FORMAT_ARGB8888 and GGL_PIXEL_FORMAT_RGBA_8888
Using drm graphics.
I:TWFunc::Set_Brightness: Setting brightness control to 420
I:Loading package: splash (/twres/splash.xml)
I:Load XML directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/splash.xml' directly
I:Checking resolution...
I:Scaling theme width 1.000000x and height 1.170833x, offsets x: 0 y: 0 w: 0 h: 0
I:Loading resources...
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Loading page splash
I:Switching packages (splash)
=> Linking mtab
=> Processing /etc/recovery.fstab
I:Reading /etc/recovery.fstab
I:Processing '/boot'
I:Processing '/cache'
I:Processing '/recovery'
I:Processing '/system'
I:Processing '/vendor'
I:Processing '/system_image'
I:Processing '/vendor_image'
I:Processing '/data'
I:FBE contents 'ice', filenames 'aes-256-cts'
I:Processing '/firmware'
I:Created '/firmware' folder.
I:Processing '/cust'
I:Created '/cust' folder.
I:Processing '/misc'
I:Processing '/modem'
I:Processing '/bluetooth'
I:Processing '/dsp'
I:Processing '/efs1'
I:Processing '/efs2'
I:Processing '/efsc'
I:Processing '/efsg'
I:Processing '/persist'
I:Created '/persist' folder.
I:TWFunc::Fixup_Time: Pre-fix date and time: 1970-04-13--01-02-20
I:TWFunc::Fixup_Time: Setting time offset from file /sys/class/rtc/rtc0/since_epoch
I:TWFunc::Fixup_Time: will attempt to use the ats files now.
I:TWFunc::Fixup_Time: Setting time offset from file /persist/time/ats_2, offset 1539800375167
I:TWFunc::Fixup_Time: Date and time corrected: 2019-01-27--19-21-56
I:Processing '/usb_otg'
I:Created '/usb_otg' folder.
I:Done processing fstab files
I:Setting up '/data' as data/media emulated storage.
I:mount -o bind '/data/media' '/sdcard' process ended with RC=0
I:mount -o bind '/data/media/0' '/sdcard' process ended with RC=0
I:File Based Encryption is present
e4crypt_initialize_global_de
calling retrieveAndInstallKey
Key exists, using: /data/unencrypted/key
```

**Comment by notsyncing** [comment]
Is there any error in dmesg?
Also full logcat as an attachment or pastebin, if possible.

**Comment by mauronofrio** [comment]
This is full logcat: https://pastebin.com/WpWGw1Jw
This is full dmesg: https://pastebin.com/AqyerYDb

**Comment by mauronofrio** [comment]
Seems it is unable to find the recovery files, but they are there, adb works, decryption works ( I'm able to see files in /sdcard), but the twrp freeze at twrp logo

**Comment by notsyncing** [comment]
```
[   21.909994] init: starting service 'sbinqseecomd'...
[   21.910826] init: cannot execve('/sbin/qseecomd'): No such file or directory
[   21.911119] init: Service 'sbinqseecomd' (pid 580) exited with status 127
[   21.911139] init: Sending signal 9 to service 'sbinqseecomd' (pid 580) process group...
[   21.911212] libprocessgroup: Successfully killed process cgroup uid 0 pid 580 in 0ms
```

According to these, I guess you did not change the dynamic linker in `qseecomd`. If it was so, please try using `sed 's|/system/bin/linker64|///////sbin/linker64|' /sbin/qseecomd > /sbin/qseecomd2` and replace `qseecomd` file with the generated `qseecomd2`.

**Comment by mauronofrio** [comment]
Thanks, it's the first time i need this tricks, i will let you know if it works or not

**Comment by mauronofrio** [comment]
Seems is not that the problem

**Comment by notsyncing** [comment]
um, could you try executing `/sbin/qseecomd` directly from adb shell and see what will happen? 
And did it result in the same error (init: cannot execve('/sbin/qseecomd'): No such file or directory) after you modified the `qseecomd` file?
Also, if `qseecom` did not run, you could try mount /system and try executing it again.

**Comment by mauronofrio** [comment]
With the new qseecomd, i will make more in tests in the night maybe

https://pastebin.com/b2gWStjf
https://pastebin.com/krHGprhF

**Comment by mauronofrio** [comment]
I solved my problems thanks for the advices

**Comment by mauronofrio** [comment]
@notsyncing you should start using toolbox instead of busybox. Actually busybox is no more updated on omni and twrp source

**Comment by notsyncing** [comment]
@mauronofrio Does toolbox have at least the same features as busybox? If not, I'd prefer keeping busybox until it's no longer buildable.

**Comment by mauronofrio** [comment]
Yes same features nad maybe a better support for the newer versions

**Comment by notsyncing** [comment]
Ok, updated in 0c63607

**Comment by simonsmh** [comment]
Beware that there might have some of the zip scripts still need busybox. It's not a good idea to drop it since it's still working. 
BTW the busybox is much useful than the toolbox since it has more features, although the toolbox is just enough for the basic function.

**Comment by mauronofrio** [comment]
Maybe yes, but you can't keep using something is not more supported, in all cases for official builds you should use toolbox
