### ISSUE TITLE
Build failure: busybox missing

### ISSUE THREAD

**Issue by Enaunimes** [notsyncing/android_device_xiaomi_polaris#14]
Failed to build with the following message: 
`ninja: error: '/home/builder/BUILD/out/target/product/polaris/system/xbin/busybox', needed by '/home/builder/BUILD/out/target/product/polaris/obj_arm/SHARED_LIBRARIES/libbmlutils_intermediates/teamwin', missing and no known rule to make it
`
I followed the instruction in the README.md. I changed the TeamWin in the manifest entry back to notsyncing, of course.

What did I miss here?

**Comment by simonsmh** [comment]
Use omnirom's busybox, branch `android-9.0`.

**Comment by mauronofrio** [comment]
You can try setting also toolbox

TW_USE_TOOLBOX := true

**Comment by mauronofrio** [comment]
There is not an omnirom busybox android-9.0 branch

**Comment by simonsmh** [comment]
Take this https://github.com/TeamWin/android_external_busybox/tree/android-9.0

**Comment by simonsmh** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
<remove-project name="platform/bootable/recovery" />
<project name="android_bootable_recovery" path="bootable/recovery" remote="omnirom" revision="android-9.0" />
<project name="TeamWin/android_external_busybox" path="external/busybox" remote="github" revision="android-9.0" />
<project name="notsyncing/android_device_xiaomi_polaris" path="device/xiaomi/polaris" remote="github" revision="android-9.0" />
<project name="LineageOS/android_kernel_xiaomi_sdm845" path="kernel/xiaomi/sdm845" remote="github" revision="lineage-16.0" />
</manifest>
```
