### ISSUE TITLE
Missing android.hardware.weaver@1.0.so

### ISSUE THREAD

**Issue by notsyncing** [notsyncing/android_device_xiaomi_polaris#15]
@simonsmh I think we should revert the `android.hardware.weaver@1.0.so`, on TWRP official build it's complaining:

```
02-09 18:16:00.860   598   598 F linker  : CANNOT LINK EXECUTABLE "/sbin/recovery": library "android.hardware.weaver@1.0.so" not found
```

or am I missing something?

**Comment by notsyncing** [comment]
Oh, I see the commits in twrp repo. Maybe they are not building with latest code.

**Comment by simonsmh** [comment]
Ask them to update it instead.

**Comment by mauronofrio** [comment]
you should start to use toolbox instead of busybox, to have a better compatibility

**Comment by mauronofrio** [comment]
I made the mi mix 2s markdown for official twrp:

https://gerrit.twrp.me/#/c/twrpme/+/600/
