### ISSUE TITLE
About Decryption

### ISSUE THREAD

**Issue by simonsmh** [notsyncing/android_device_xiaomi_polaris#2]
作者你好，关于解密的事情我想再咨询一下，因为看到目前还是使用predecrypt.sh的，没有类似其他机型用keystore的so和别的东西。我自己尝试时在system.img看到了相关的so（keystore.default.so），但是还是卡在开机解密上，想请问一下如何解决这方面的问题（

**Comment by notsyncing** [comment]
我是把小米6的predecrypt.sh拿过来再根据twrp的日志改了下的，当时是从日志里看到android.hardware.gatekeeper@1.0-service-qti和android.hardware.keymaster@3.0-service-qti这两个服务起不来导致无法解密，然后我就在adb下手动运行它们再看logcat缺哪些文件这样弄的

你可以在编译时打开logcat，再提供下日志看看
