### ISSUE TITLE
TWRP下手机连接电脑，然后双清后重启到twrp卡死

### ISSUE THREAD

**Issue by timesleader** [notsyncing/android_device_xiaomi_polaris#4]
作者你好，发现845的机器自从修复了触摸卡顿....之后有个新bug，手机插在接电脑上，然后点击twrp里面的清除 进行滑动按钮恢复出厂操作也就是双清，之后重启到twrp就会出现卡死的现象。。。更奇怪的是有时候没双清也有一定概率插电脑就睡死。。。

**Comment by notsyncing** [comment]
这个问题已经有人反馈过了，我自己也遇到过，而且无法取得日志，所以迄今为止原因仍然不明。。。估计还是跟TWRP那边的 `34ad728` 这个提交有关系

**Comment by timesleader** [comment]
这个提交导致的
16d831bee5a660f5ac6da0d8fff2b3ec4697d663
这个虽然修复了卡顿但是连电脑卡死也出现了，这个提交之前的唯一bug就是卡顿。感谢哥们回复。还是等官方修复吧，对了很感谢，参考你的修改震动可以用了，845你做了很大贡献。




------------------ 原始邮件 ------------------
发件人: "Song Fuchang"<notifications@github.com>;
发送时间: 2018年6月7日(星期四) 上午9:34
收件人: "notsyncing/android_device_xiaomi_polaris"<android_device_xiaomi_polaris@noreply.github.com>;
抄送: "A专业远程刷机18855521236"<1449626263@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [notsyncing/android_device_xiaomi_polaris] TWRP下手机连接电脑，然后双清后重启到twrp卡死 (#4)




这个问题已经有人反馈过了，我自己也遇到过，而且无法取得日志，所以迄今为止原因仍然不明。。。估计还是跟TWRP那边的 34ad728 有关系

**Comment by notsyncing** [comment]
`16d831b` 是给DRM显示加了双缓冲，后面的 `34ad728` 是等待缓冲区切换完成，但在mix2s上这个提交会导致开机黑屏，可参考 https://github.com/omnirom/android_bootable_recovery/issues/219 ，已经被revert了。我猜现在这个随机卡死是因为没等待缓冲区切换完成所造成的某种冲突导致的，不过改这种bug已经超出我的能力范围了。。。相对于之前的严重卡顿而言，我觉得只是可恢复的卡死已经算可以接受了

总之坐等TWRP官方修复吧。

**Comment by timesleader** [comment]
对了老外为了解决插电脑卡死 直接拿掉了MTP功能！！！

**Comment by notsyncing** [comment]
有出处可以参考么？

**Comment by timesleader** [comment]
他device还没放出来，我只是对比了下文件 少了libtwrpmtp.so 刚好我怀疑是adb 或者mtp和这个冲突，试了下果然是，razer phone twrp官方也是这么干掉了mtp  配置文件加一加:TW_EXCLUDE_MTP := true 坏处是mtp拿掉了刷机不是很方便小白不会用adb推送包

**Comment by notsyncing** [comment]
那我先编译一个不带mtp的版本放出去试试

**Comment by notsyncing** [comment]
去除MTP后好像确实没有卡死的问题了，这两天也没有人再反馈会卡死，我自己也再没遇到过，看来这确实是一个可行的临时解决方案。非常感谢你的建议！

然后，我们还是坐等TWRP修复吧。。。

**Comment by simonsmh** [comment]
话说ADB的更加neat些解决方案有么
目前的方法总感觉是dirty hack

**Comment by notsyncing** [comment]
嗯，禁用MTP肯定不是长久之计，但在没有日志的情况下完全摸不到头脑，我看OP6的twrp也是这么干来解决无响应问题的：

https://www.xda-developers.com/official-twrp-oneplus-6-huawei-p20-pro/

```
MTP support is currently disabled in TWRP as it causes a kernel panic with stock kernel. Perhaps a future update will fix this issue.
```

我猜mix2s可能也是一样的问题。如果有人能接受失去保修或彻底变砖的风险，拆机从串口导出日志的话。。。说不定有法子

**Comment by timesleader** [comment]
目前845的机器一个都逃不掉这个bug，twrp官方都束手无策，想必难度很大。主要你没有机会去看日志。。.

**Comment by notsyncing** [comment]
BoardConfig.mk:

```
BOARD_KERNEL_CMDLINE := console=ttyMSM0,115200n8 earlycon=msm_geni_serial,0xA84000 
```

如果能找到串口`ttyMSM0`，就有内核日志，不过没人愿意干，包括我。。。
