### ISSUE TITLE
显示模式虽然正确了，但是截屏出来的图还是颜色不对

### ISSUE THREAD

**Issue by wzsx150** [notsyncing/android_device_xiaomi_polaris#5]
虽然设置了BGRA_8888可以让显示颜色恢复正常，但是截屏出来的图片还是颜色不对，不知道大佬是不是也这样，估计也需要twrp修复一下？

**Comment by notsyncing** [comment]
我还真没注意过TWRP还有截图功能。。。去试了一下颜色果然不对

https://gerrit.omnirom.org/#/c/android_bootable_recovery/+/31042/
请试下这个提交，我自己试了下截图颜色正常了

**Comment by wzsx150** [comment]
恩呢，明白，就是也修改截屏的显示模式
