### ISSUE TITLE
Won't boot after 8.7.16

### ISSUE THREAD

**Issue by simonsmh** [notsyncing/android_device_xiaomi_polaris#8]
RT.
Working last week. More info needed.

**Comment by notsyncing** [comment]
I did not find a 8.7.16 download link. Would you mind send me a link?

**Comment by simonsmh** [comment]
bigota.d.miui.com/8.7.16/miui_MIMIX2S_8.7.16_af391fa0df_8.0.zip
不好意思刚刚没看见

**Comment by notsyncing** [comment]
请试下这个：https://pan.baidu.com/s/1hZQYNZWxekEc1AxUydPSFg
我把内核替换成了8.7.16的，在我的设备上可以启动了

**Comment by simonsmh** [comment]
百毒网盘下载太慢了，我自己换了个kernel编译了一下，确实能启动了。
是用这个内测版的kernel呢还是等周五的开发版？

**Comment by notsyncing** [comment]
抱歉，我还以为百毒网盘能快一点。。。那就先等周五的开发版吧
